Existe correlação entre a transmissão do COVID-19 e a densidade demográfica da população à nível municipal e estadual no Brasil?

R. Sim, dependendo da quantidade de pessoas, a contaminação é maior devido ao maior número de pessoas que um infectado pode entrar em contato, principalmente em locais de maior aglomeração (Transporte público: ônibus e metrô). (Eloiza)

In [1]:
import pandas as pd

In [5]:
#Importando o arquivo contendo dados de covid por regiões do BR
corona_BR = pd.read_csv('../covid/COVID19_REGIOES BR.csv', sep=';')
corona_BR.head()

,regiao,estado,data,casosNovos,casosAcumulados,obitosNovos,obitosAcumulados
0,Norte,RO,30/01/2020,0,0,0,0
1,Norte,RO,31/01/2020,0,0,0,0
2,Norte,RO,01/02/2020,0,0,0,0
3,Norte,RO,02/02/2020,0,0,0,0
4,Norte,RO,03/02/2020,0,0,0,0

In [9]:
#Filtrando apenas os dados referentes ao estado de São Paulo
sp = corona_BR[(corona_BR['estado'] == 'SP') & (corona_BR['casosNovos']!=0)]
sp

,regiao,estado,data,casosNovos,casosAcumulados,obitosNovos,obitosAcumulados
1243,Sudeste,SP,26/02/2020,1,1,0,0
1246,Sudeste,SP,29/02/2020,1,2,0,0
1250,Sudeste,SP,04/03/2020,1,3,0,0
1251,Sudeste,SP,05/03/2020,3,6,0,0
1252,Sudeste,SP,06/03/2020,4,10,0,0
1253,Sudeste,SP,07/03/2020,3,13,0,0
1254,Sudeste,SP,08/03/2020,3,16,0,0
1256,Sudeste,SP,10/03/2020,3,19,0,0
1257,Sudeste,SP,11/03/2020,11,30,0,0
1258,Sudeste,SP,12/03/2020,12,42,0,0
1259,Sudeste,SP,13/03/2020,14,56,0,0
1260,Sudeste,SP,14/03/2020,9,65,0,0
1261,Sudeste,SP,15/03/2020,71,136,0,0
1262,Sudeste,SP,16/03/2020,16,152,0,0
1263,Sudeste,SP,17/03/2020,12,164,1,1
1264,Sudeste,SP,18/03/2020,76,240,3,4
1265,Sudeste,SP,19/03/2020,46,286,0,4
1266,Sudeste,SP,20/03/2020,110,396,5,9
1267,Sudeste,SP,21/03/2020,63,459,6,15
1268,Sudeste,SP,22/03/2020,172,631,7,22
1269,Sudeste,SP,23/03/2020,114,745,8,30
1270,Sudeste,SP,24/03/2020,65,810,10,40
1271,Sudeste,SP,25/03/2020,52,862,8,48
1272,Sudeste,SP,26/03/2020,190,1052,10,58
1273,Sudeste,SP,27/03/2020,171,1223,10,68
1274,Sudeste,SP,28/03/2020,183,1406,16,84
1275,Sudeste,SP,29/03/2020,45,1451,14,98
1276,Sudeste,SP,30/03/2020,66,1517,15,113
1277,Sudeste,SP,31/03/2020,822,2339,23,136
1278,Sudeste,SP,01/04/2020,642,2981,28,164
1279,Sudeste,SP,02/04/2020,525,3506,24,188

In [10]:
#Ultima atualização de obito
sp.loc[sp.index.max(),'obitosAcumulados']

188